{{ pkci.default = 'normal' }}
{{- pkci.name = ( env('PROJECT_NAME') | default('PKCI') ) }}
{{- pkci.description = ( env('PROJECT_DESCRIPTION') | default('Pumped Kaniko Container Image for Continuous Integration') ) }}
{{- pkci.author = ( env('PROJECT_AUTHOR') | default('WoozyMasta <me@woozymasta.ru>') ) }}
{{- pkci.timestamp = command('date', '-uIs') }}{{ pkci.timestamp = ( pkci.timestamp.stdout | trim ) }}
{{- pkci.year = command('date', '+%Y') }}{{ pkci.year = ( pkci.year.stdout | trim )}}
{{- pkci.sha_commit = command('git', 'rev-parse', 'HEAD') }}{{ pkci.sha_commit = ( pkci.sha_commit.stdout | trim ) }}
{{- pkci.upx_enabled = ( env('PROJECT_UPX_ENABLED') | default('true') ) }}

{%- if env('PROJECT_TYPE') | default(pkci.default) == 'slim' %}
{{-   pkci.type = env('PROJECT_TYPE') }}{{ pkci.mode = 0 -}}
{% else if env('PROJECT_TYPE') | default(pkci.default) == 'extra'%}
{{-   pkci.type = env('PROJECT_TYPE') }}{{ pkci.mode = 2 -}}
{% else %}
{{-   pkci.type = pkci.default }}{{ pkci.mode = 1 -}}
{% end if %}

{%- if env('PROJECT_VERSION') | default('') | length > 0 %}
{{-  pkci.version = env('PROJECT_VERSION') }}
{{-  pkci.tag = env('PROJECT_VERSION') }}
{% else %}
{{-  pkci.version = ('latest+' ~ pkci.sha_commit) }}
{{-  pkci.tag = 'latest' }}
{% end if -%}

# {{ pkci.name }} {{ pkci.type }}{% if pkci.upx_enabled == 'true' %} (UPX){% end if %}
# {{ pkci.description }}
# =========================================================================
#
# License: MIT
# Copyright {{ pkci.year }} {{ pkci.author }}
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
#
# =========================================================================
{{ file('./src/.generated') | trim }}
# Generated at: {{ pkci.timestamp }}
# =========================================================================

ARG VER_KANIKO={{ env('VER_KANIKO') | default('1.8.1') }}
ARG VER_BUSYBOX={{ env('VER_BUSYBOX') | default('1.34.1') }}

{%- if pkci.mode > 0 %}
ARG VER_GO={{ env('VER_GO') | default('1.18') }}
ARG VER_COSIGN={{ env('VER_COSIGN') | default('1.9.0') }}
ARG VER_NOTARY={{ env('VER_NOTARY') | default('0.7.0') }}
ARG VER_OPENSSL={{ env('VER_OPENSSL') | default('3.0.3') }}
{%- end if %}

# == Kaniko ==
# ============
FROM gcr.io/kaniko-project/executor:v$VER_KANIKO AS kaniko

# == Busybox ==
# =============
FROM docker.io/busybox:$VER_BUSYBOX AS busybox
{%- if pkci.mode > 0 %}

# == OpenSSL ==
# =============
FROM docker.io/ep76/openssl-static:$VER_OPENSSL AS openssl

# == Cosign ==
# =============
FROM gcr.io/projectsigstore/cosign:v$VER_COSIGN AS cosign

# == Notary-signer ==
# ===================
FROM docker.io/notary:signer-$VER_NOTARY AS notary
{%- end if %}

# == Binaries ==
# ==============
{%- if pkci.mode > 0 %}
FROM docker.io/golang:$VER_GO-bullseye AS binaries
{%- else %}
FROM docker.io/debian:bullseye AS binaries
{%- end if %}

{%- if pkci.upx_enabled == 'true' %}
ARG VER_UPX={{ env('VER_UPX') | default('3.96') }}
{%- end if %}
ARG VER_BASH={{ env('VER_BASH') | default('5.1.016-1.2.3') }}
ARG VER_PUSHRM={{ env('VER_PUSHRM') | default('1.8.1') }}
ARG VER_HADOLINT={{ env('VER_HADOLINT') | default('2.10.0') }}
ARG VER_JQ={{ env('VER_JQ') | default('1.6') }}
ARG VER_CURL={{ env('VER_CURL') | default('7.83.1') }}

{%- if pkci.mode > 0 %}
ARG VER_MDTOHTML={{ env('VER_MDTOHTML') | default('latest') }}
ARG VER_OPENSSL={{ env('VER_OPENSSL') | default('3.0.3') }}
ARG VER_CRANE={{ env('VER_CRANE') | default('0.9.0') }}
ARG VER_TEMPLAR={{ env('VER_TEMPLAR') | default('0.5.1') }}
ARG VER_TOKEI={{ env('VER_TOKEI') | default('12.1.2') }}
{%- end if %}

{%- if pkci.mode > 1 %}
ARG VER_YQ={{ env('VER_YQ') | default('4.25.2') }}
ARG VER_TRIVY={{ env('VER_TRIVY') | default('0.29.2') }}
ARG VER_GOMPLATE={{ env('VER_GOMPLATE') | default('3.11.1') }}
ARG VER_KUBECTL={{ env('VER_KUBECTL') | default('1.24.1') }}
ARG VER_HELM={{ env('VER_HELM') | default('3.9.0') }}
ARG VER_JSONBUILDER={{ env('VER_JSONBUILDER') | default('0.5.1') }}
ARG VER_TANKA={{ env('VER_TANKA') | default('0.22.1') }}
ARG VER_KUBELINTER={{ env('VER_KUBELINTER') | default('0.3.0') }}
ARG VER_KUBESEC={{ env('VER_KUBESEC') | default('2.11.4') }}
{%- end if %}

# hadolint ignore=DL3008
RUN set -eux && \
    apt-get update && \
    apt-get install --no-install-recommends -y curl ca-certificates xz-utils {%- if pkci.upx_enabled == 'true' %} && \
    curl -sLo upx.tar.xz \
      "https://github.com/upx/upx/releases/download/v$VER_UPX/upx-$VER_UPX-amd64_linux.tar.xz" && \
      tar -xvf upx.tar.xz --strip-components=1 "upx-$VER_UPX-amd64_linux/upx" && \
      chmod +x upx && \
      cp upx /usr/local/bin/upx && \
      rm -f upx.tar.xz
{%- end if %}

WORKDIR /kaniko

# Kaniko
RUN mkdir -p bin ssl .docker {% if pkci.mode > 0 %}.config{% end if %} {% if pkci.mode > 1 %}.kube .cache{% end if %}
COPY --from=kaniko /kaniko/executor ./executor
RUN ln -s /kaniko/executor /kaniko/bin/kaniko {%- if pkci.upx_enabled == 'true' %} && \
    upx --no-progress --no-color /kaniko/executor && \
    upx -t --no-progress --no-color /kaniko/executor
{%- end if %}

WORKDIR /kaniko/bin

{% if pkci.mode > 0 %}
# Kaniko credential helpers
COPY --from=kaniko /kaniko/docker-credential-* ./
{% end if %}

# Busybox
COPY --from=busybox /bin/ ./
{%- if pkci.mode > 0 %}
# OpenSSL
COPY --from=openssl /usr/bin/openssl ./openssl
# Cosign
COPY --from=cosign /ko-app/cosign ./cosign
# Notary
COPY --from=notary /notary/signer/notary-signer ./notary-signer
{% end if %}

RUN set -eux && \
{#- SLIM #}
    curl -sLo bash \
      "https://github.com/robxu9/bash-static/releases/download/$VER_BASH/bash-linux-x86_64" && \
    curl -sLo hadolint \
      "https://github.com/hadolint/hadolint/releases/download/v$VER_HADOLINT/hadolint-Linux-x86_64" && \
    curl -sLo pushrm \
      "https://github.com/christian-korneck/docker-pushrm/releases/download/v$VER_PUSHRM/docker-pushrm_linux_amd64" && \
    curl -sLo jq \
      "https://github.com/stedolan/jq/releases/download/jq-$VER_JQ/jq-linux64" && \
    curl -sLo curl \
      "https://github.com/moparisthebest/static-curl/releases/download/v$VER_CURL/curl-amd64" {%- if pkci.mode > 0 %} && \
{#- NORMAL #}
    go install github.com/gomarkdown/mdtohtml@$VER_MDTOHTML && \
      mv /go/bin/mdtohtml mdtohtml && \
    curl -sLo crane.tar.gz \
      "https://github.com/google/go-containerregistry/releases/download/v$VER_CRANE/go-containerregistry_Linux_x86_64.tar.gz" && \
      tar -xvf crane.tar.gz crane && \
      rm -f crane.tar.gz && \
    curl -sLo templar.tar.xz \
      "https://github.com/proctorlabs/templar/releases/download/v$VER_TEMPLAR/templar-x86_64-unknown-linux-musl.tar.xz" && \
      tar -xvf templar.tar.xz templar && \
      rm -f templar.tar.xz && \
    curl -sLo tokei.tar.gz \
      "https://github.com/XAMPPRocky/tokei/releases/download/v$VER_TOKEI/tokei-x86_64-unknown-linux-musl.tar.gz" && \
      tar -xvf tokei.tar.gz tokei && \
      rm -f tokei.tar.gz {%- end if %}{% if pkci.mode > 1 %} && \
{#- EXTRA #}
    curl -sLo yq \
      "https://github.com/mikefarah/yq/releases/download/v$VER_YQ/yq_linux_amd64" && \
    curl -sLo gomplate \
      "https://github.com/hairyhenderson/gomplate/releases/download/v$VER_GOMPLATE/gomplate_linux-amd64-slim" && \
    curl -sLo kubectl \
      "https://storage.googleapis.com/kubernetes-release/release/v$VER_KUBECTL/bin/linux/amd64/kubectl" && \
    curl -sLo helm.tar.gz \
      "https://get.helm.sh/helm-v$VER_HELM-linux-amd64.tar.gz" && \
      tar -xvf helm.tar.gz --strip-components=1 linux-amd64/helm && \
      rm -f helm.tar.gz && \
    curl -sLo trivy.tar.gz \
      "https://github.com/aquasecurity/trivy/releases/download/v$VER_TRIVY/trivy_${VER_TRIVY}_Linux-64bit.tar.gz" && \
      tar -xvf trivy.tar.gz trivy contrib && \
      mv contrib ../contrib && \
      rm -f trivy.tar.gz && \
    curl -sLo kube-linter \
      "https://github.com/stackrox/kube-linter/releases/download/$VER_KUBELINTER/kube-linter-linux" && \
    curl -sLo kubesec.tar.gz \
      "https://github.com/controlplaneio/kubesec/releases/download/v$VER_KUBESEC/kubesec_linux_amd64.tar.gz" && \
      tar -xvf kubesec.tar.gz kubesec && \
      rm -f kubesec.tar.gz && \
    curl -sLo tk \
      "https://github.com/grafana/tanka/releases/download/v$VER_TANKA/tk-linux-amd64" && \
    curl -sLo jb \
      "https://github.com/jsonnet-bundler/jsonnet-bundler/releases/download/v$VER_JSONBUILDER/jb-linux-amd64"
{%- end if %}

{% if pkci.upx_enabled == 'true' %}
# hadolint ignore=DL4006,DL3059
RUN set -eux && \
    chmod -cR a+x,u+w,go-w ./ && \
    chown -cR 0:0 ./ && \
    find ./ -executable -type f -links 1 -print0 | xargs --null -- upx --no-progress --no-color || true && \
    find ./ -executable -type f -links 1 -print0 | xargs --null -- upx -t --no-progress --no-color
{%- else %}
# hadolint ignore=DL3059
RUN chmod -cR a+x,u+w,go-w ./ && \
    chown -cR 0:0 ./
{%- end if %}

# SSL
WORKDIR /kaniko/ssl/certs
RUN cp /etc/ssl/certs/ca-certificates.crt ./
{%- if pkci.mode > 0 %}

# OpenSSL
WORKDIR /kaniko/ssl
RUN curl -sLo openssl.cnf \
      "https://raw.githubusercontent.com/openssl/openssl/openssl-$VER_OPENSSL/apps/openssl.cnf"
{%- end if %}

# == Build Image ==
# =================
FROM scratch

# Binaries
COPY --from=binaries /kaniko /kaniko
COPY /src/bin /kaniko/bin
ENV PATH /usr/local/bin:/kaniko/bin:/kaniko
# hadolint ignore=DL4005
RUN ["/kaniko/bin/sh", "-c", "set -eux && mkdir -p /bin /usr/bin && ln -s /kaniko/bin/sh /bin/sh && ln -s /kaniko/bin/bash /bin/bash && ln -s /kaniko/bin/env /usr/bin/env"]
VOLUME /kaniko

# nsswitch
COPY --from=binaries /etc/nsswitch.conf /etc/nsswitch.conf

# Certificates
ENV SSL_CERT_DIR=/kaniko/ssl/certs
ENV SSL_CERT_FILE=/kaniko/ssl/certs/ca-certificates.crt

{%- if pkci.mode > 0 %}
# OpenSSL config
ENV OPENSSL_CONF=/kaniko/ssl/openssl.cnf
{%- end if %}

# Environments
ENV HOME /root
ENV USER root
ENV DOCKER_CONFIG /kaniko/.docker/
{%- if pkci.mode > 0 %}
ENV DOCKER_CREDENTIAL_GCR_CONFIG /kaniko/.config/gcloud/docker_credential_gcr_config.json
{%- end if %}
{%- if pkci.mode > 1 %}
ENV KUBECONFIG /kaniko/.kube/config
ENV TRIVY_CACHE_DIR /kaniko/.cache
{%- end if %}

WORKDIR /workspace

# Labels
ARG TIMESTAMP={{ env('TIMESTAMP') | default(pkci.timestamp) }}
LABEL org.opencontainers.image.created="$TIMESTAMP"
LABEL org.opencontainers.image.url=ghcr.io/woozymasta/pkci:{{ pkci.tag }}
LABEL org.opencontainers.image.version={{ pkci.version }}
LABEL org.opencontainers.image.title={{ pkci.name }}
LABEL org.opencontainers.image.description="{{ pkci.description }}"
LABEL org.opencontainers.image.authors="{{ pkci.author }}"
LABEL org.opencontainers.image.documentation=https://github.com/WoozyMasta/pkci
LABEL org.opencontainers.image.revision={{ pkci.sha_commit }}
LABEL org.opencontainers.image.licenses=MIT

ENTRYPOINT ["/kaniko/executor"]

# =========================================================================
{{ file('./src/.generated') | trim }}
# Generated at: {{ pkci.timestamp }}
# =========================================================================
